[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "93cdfa1dc4ee6317de02b9f00c6ecdad85d42112"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "a7be4567a56e27ba7c012a1c28ec087af39ec1fe0f0243eba6d15b3b894d45c0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a29eb6806c165d54a5e5bd770f0ea580fd30ec4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6a018635c62592ebc410cd631246924a679f0af497a80e7256592170da092843"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7619f181f39b7f66efabb7a4aa4d54f37252724"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e068a4dc5106ed9b53a7d73742bd4b2d8f60ac8e47ca4ad145f84da0005a701c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "c45d6e03a55137d645258a242f57e641be027206"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "66a7ea3b8bd6386508bfb056151a338be6533166e74cf6d0e2e6c177316cf2d2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e499ddb483b4c81429320872f8d9e804ae34b79"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9b0e1b8324ca3a5e92dce66e01beaa731f78c97517a8db63701c4ae32b5bde8b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6528e4af9929e966e627ee1bfc0abf36bf36b6b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e952cb8d1c0a2c47e4830480cefc688e133cc7dfd285e265219f5f8cb481513d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1881b8e079f3888722aa81ca29aa20b4b2c028f0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1210d42a0bd834ef4a9efbfc0ebcc0e64a699dc5161569f519dea71a9c528f9b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd7216f04d7a91542cd5c7adaa32a91cbd84a956"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1b66de94cc0d6319ffe3fc927bac627c8072a4e03d17305f6a2717951a29583d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4832b15fd59a43775e19181e5d2562cced3b1340"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "39bb61713ef1a4f54cdcc187ffaccb6071aa45113e8621dd52017207bcf91337"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "477937f6dcb2547e87ecd1a2b33384d946a2bd14"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "46c855c2a8045f8cd1f53d2159294465995178ff4ae65fa72ba10b9500074781"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbc284283dd203f0f7b86efb5eca535307a3ac44"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "56214f74f55d45be438e524ceb39f96ed36efd7d2282ba37a2bfdfc644a20a1a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "413dda4773379a1d3b0591d742e6078a75c54041"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "a4b9fc838e83c6fbf8c313b4132b59c052413661e503764820d92259fb1280f0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a6b1d4478c350e25aaba8035419c2ce9d526405"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "456277de80b23c2420b988fd4293e5ce8f96d50ca19454cd358f99672a23fdf6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "f31c0a424be219224ff97a2ec2bf2c7100e358a1"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "dd91115203174b966ced4da5c90b331c075815401d6af3ef6e907ac0f51977bd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd7464f08ceba90089bbff1d71085624bf4dccf2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b4ce19b139bf82f117ea79a90192918c485a6c88c38a037b5129dfa441f5c8c4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "897cba39557392b343ebe1eb5534da30bfb00df9"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "feac15246978352be0ea6f00abbf8a31bb4b0b9b7faec0c29226f44d474dbbda"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "ad34d8a3640e9827459da3bc578712629ecdf81f"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f029a5668571b5320631f95e30f3fc1997cbe60d30c89082d96fb63189db5402"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45cdc699287de7954a31a60a5f0e3e0a4515f769"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c2a4d09b320586f9cad9ee910a5d310da7c709c0efaff372415b6d267620ad36"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v21.1.4+0/SPIRV_LLVM_Backend.v21.1.4.x86_64-w64-mingw32-cxx11.tar.gz"
