[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "cf8b352fde77149aeb043c611cb23a52086bae39"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "86b7b81f346149cae36f014c0da1b42ff922f4cc3b71591eede20eeeb064671c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "295d281a70b062a6dbc37e095a2a23076f2de616"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ad1d8e192faa11744af06f5c103f14ffd6242e2090ec2c309dfa4334414b10f4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f07f7524099ef20f2887ab99dced888753b754a2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "dce32da99b4016d9997ac26fd4b904c471a1f0a6bc2106b813db93ab1560fe41"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "093a31c807e36ba54b352df70e068374906ae4e6"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "29cc415ffda92146dc9854184aa4ea3819b67edd976e75a6f5d3f4a7c95f1347"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e96f1783c3f9188428bb730d25c125183177d6fd"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "90e18985382d6e0fd3a5a29216975392b58f9e03265021763442f29a435878af"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "b099bb14bfb21581d865b38347f17f48bf333973"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "027c891c0a3303cf4ee481a302aaccaf6813b119164d80b327837ce61c68c884"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33ab229f9b8c27b631f044d629fbded75367abf0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8d57b493403c718dcd418cd8da9777c76c2825484aacf1c6dfcb7ca44018dce4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13c6368e7fe4e241b2d156244802c234dccc4c13"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "301445cdb14a14168eeb12a64fa407a79d123df862a5b9c971d029b15936cfb0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3d41b856f60d5f282ba5b1e4c2eaf4915449dfc"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9573fe2bccbecbd7b6548109ba8f71623ea2e65584030c88737749ef7f118dbb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b0f9365d4e1107ccf6ab5c94a92bcf7f3913832"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "fbbf0e964cd43bd22500241831e23b417d57cebb897ec4962309ca70c36ca9c8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c11cc93751b0c5e9f0a29737e8303b9445c481d2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "efa24fab2c3b22c6db6a27a52693e09e03e225a263a864af08be5fd2060c647c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b95aaa23c0f5ee0ee00f72c28cc79a45c1d3265c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ffd5463c73dcf483a78e677b58910421f98f5377464c53ace879985826964fe0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6855b1825bd9b62a39bbd80c0e271c39b9b168e3"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8b92784f03307917cbd4cf1761dd170404baa34bbdf7890f31db77d6275ccc07"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f22ec9c8ccb7076c3cfe492ed60a75e48df3368c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b9ae02076529722094f2683178d78dc08f35e9a32d6333163f712e67cff98657"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59b05c57029494c82537db242ac2cf9dde7fe4b4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d400cbd997f52cd1f4337028e3b760be5aca5b3e7bce9bd308507427563bba6b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dabb3facb07de1eb4cce80bad483ad924bf00ef0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ea0e4f28c9992d79e93f0fe47541e969c872703b9d7013c638c2a1d5d117a11c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7a2642e9b4223a12dbfec08ce0bd1174167558a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1547d71c8fc105175029f38314478aeb0b3a7c20081315fcb1ec75e0dd107458"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "296c7244718dc4fcd87cb12c377de52fd126e3a7"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f164521413dca3a6d34b78b3d9d017a27a7827fc2c96eea4036fb48f5c309520"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec8fdc9a3a73ea7911aec502336af457a033c39f"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e94cd57eb0613c9b5419872351a47a660cbdf2a37f356d3faffbf0925d60818a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acbe5a56bcf6f1c0a1e9b3b1f49b7cb3121c302c"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f95e4eab06d58cc65714485806a3d84def36f6b3b23186a4a7ac6fa1d609a1d4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce55ea5003d8f94bc80a4f9e8509e04524522991"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "be8c77228873096bee2f830bcb0da38d944a7e3791ed352a076fd964a2e78dad"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bac38d152902d84eb5cd06eeb7c9077e78cf9f61"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "29f9d0cd3d746c2f4bd10e436897a6e44eb557dbc8e265c20396794faf58fe51"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4db9ebefd75f80be78a1d6910eca5907bf1eab2d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "258240cd992f808dcd73b58d07aad0ebd504aae120a4b0f4c7557f4a7279a4e4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dc6d10b89b1007082cef440432e2c6fbf937f59"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4ea6ab6e495c4f78f35240435a867709a77de8cc3665aeec2c1282a9d91d2747"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "e72762c2cefcfe756ed1d48f82426b869ca3c22a"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e9ac6c8df91db4c966ccf5c666307878fc2017b3e4367db1cdcb20c4469d3617"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60cad184cac6d55faffde447c1045bbdb37aac7d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c23b59c17a31ed8811e5f6581a1fc5fcb7230739364f982373cea758069e12b5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6a08653cd5335c4a611054885a04977c7f196c0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "783cb9bf36776c6b1ee0d6a27c8eebb580bb7ad97b5b6e706fd78ca0fb07754a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d77e2e5b47257937889b3100fc21aaec4a3a502"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ee61448c730761884ae5fc8a7fa409006956ad04832f437d3f5447f3329d69b7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbd6aea30dda948c9e4a0e2cffdfc93f7368d95a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f9919b7a81e5fe82341125765403546f6463493427d4d8c2f25676d75fcf67e8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "9752d9c7c13957f2641c9155266ab9bf99d6a969"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c63f049a6dfe6d5afe1eae65da42ab2a52658347ed761e174d76a5dde2a02172"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e0f910f7c6075aad4776828ab553c8db14bb660"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "3e07acec63c11603937747c1ed2c695bd65d08ec3ce36fb61dfacc7326faa901"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c37dfd95635bcf7155d25a1e0814c5cd7cea15d7"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "00b89e97ba09179827549f85ead1a0eff4ef3c50919efe51bcb8f9e4d33382bd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+2/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
