[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "36e00d729a2ad86d12bcd084a361c80dd4005f95"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "16a284c379ca3a32464179f78ae830c05af85c18d207aec40dbcd827f633dc21"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22e85f1193823a08998df1d229ce4d51b75e563c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c1da6ce03aa3e9bf113bddae7a35d723289ceb89721f03def6fe270024df6e22"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19d4bceefb5b1321320208cf93585283875f1137"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6d9f7de4fc118a4de6f2e06295cf3a76683f608fa5369ddb06a90e1a127ef248"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "174f115e2d1548adde56893505c9030639ebfaa7"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "3c39e4455a833196d880df6f8ce8c48897c7c1e8a66d9863fb464d416bc62023"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2f6fdf6cfcac2041b798115e90222177b3086c8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "a23c0ae096421565ca3d321edcfc1a5434d892e47e7578dc0bbfcc9632dd5491"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "121065f35577edc997f0147dedf82da9929fffd8"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d6925e9d9415f56a3c48206baca88bd5131767d45f329e7da5cbb9da39d5a830"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4973f52308a4c3db07aef4be29ba51a506b3701e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8bc8e95b2e1c10596f291a7b344e8e63286e4e2c7214920eee78d18b37be1a37"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d9fd7bd1cdc44f4c5ae429df493efa88842c67b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "23f48c7e79e2f7eb55e74f61c3228c054858d56e15e78d4a3ad4e004d243a4b4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71365db17ae653a3b3ff634cf69f63cae837b533"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4d707ad9c05cb3efb0cd630139a9ab57ee5a3fe9faf73ab039bee242106d8a44"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f5274ab29f27a141508b0a5b91dbb27e1ed0463"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "21eabf8df28a613865ea3516fc13c072acf759083e1f46612e9388486e094d7a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a06acf7e90b14a98fd40ae8b30df4c3e4431ae39"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c759b13f5883276b762389e04c06d24794176f5c37b91693ac00ca09acaeebfc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dfe26c5c01f2426401dd0b7815dff1e7044d172"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b57ced0aad4aee4259732b7b539626346d7c9b548234ebfaf5d04af59ebde18e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "909cb8c354d2e05b3c398a33eb0aa71815406ee4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ec5be8812776ad52ead71f7f15b536246eee7112b940e710d450d0e8bad48522"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "cbedb90b30b718d4026b6aa6d46707cbbb354349"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4ac9364859fdc2ac84c171f4f18c0fd564fb2e7282d212dbc56c5827ed01a337"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1f23ea20454ce8dbba12ceb574519da0e09d20b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "47c288eb3090ccee639707dc8e0cf57ad5a47146b2fa9437487a73a1d8d78f61"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a368965eb796e2087ab8f03383d4c1442322fbf"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "643eade9f086d2fd60222fcc475a92244eaf64a71d8185fed03bd9634c377df1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "6363581267d1623a0ee6fe1343e45f26cd3bcac4"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "619adc1b65b2b3b3ce604895808c94135d243da3e4d8b82d1505a19177832ab6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39897d67802aae351eb9cf9e6bef42788f54cf87"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "39059ab8194c5aace2f80aa4b855d2f3c396fa2b6fc369e1c5c31c56d3ae9904"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.8+1/SPIRV_LLVM_Backend.v22.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
