[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "7e201cfa6d936b4c89fcf2b1853006486dc7e8d5"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9c9d680ee5c883d1285ee1fa2eecad747ad4bff1a2e399e3d213a7325cf40c93"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43f74f9e58a1b0e56d01c061bdf2477d220f53f5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "60f3f151a4f11851adcb7b65e4300d9b7fc967f5c3b688025a3a0120ccea933e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9132747010e5f15c080b53dcc6c1ef28a227a53e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1004397df0774f1b757a37be9cdf272af6a4e3a5ee3cb7a1ce2d77f69ad9e90e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "073396860eed72be9cafb92ed7b27c791973345e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1953dd69605497fe8c6da0b75faf398b38f57f24fc279e98904bba32fe6fd905"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef6f42fafa97b56d2dabdfa62f59ba17b0cb6323"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "88c6d0966ea3f6f8cce04bf8aa052fb9a753afeac58976329eecfb446b0f2cea"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "63f7e00cdd9b49536535ef2ffe6c2560cdf3a2e3"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d2c256c4eac9698471b1cf48a0bae67ed3487d0f52d9f4bfe46d590460278646"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ffd05779c7edc3eceb4af9274a8f163b5237ebc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "604c8a867975e0565f92893dca1222e4790235ce636419ef210db1fd59170371"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d07753ae41dc9e6c8338b50ca3f1f545608ccfb1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b8dc18f66a46caed058d7c88b155e2730cab0ea37779751d385c98c46d35a8b6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b90ec4e70121acb8c17c41bc034b39f84d03427"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ad42149713345d02e51c54431a49d96ded0c887a43eeac8c383fb7fd64b6203d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f4e9651f75dcb056f6be037850ef619a34cb9ff"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "3fbeff3704757ca5568cfdbcf0de88f949c03cced3b7d7851abc778731dba160"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47b529e8fdf244ddeb1bffc040a150a71b8cb3bf"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "2d757ea4a0e8005e814f8c16220bd3fa7bc55c6d8aaa5233a0c8892c26e2f976"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d941add90dd03fce9541560d146b76485449e1e1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9aac46e35aec3643bb6ee49be42c1f0fe8d2c26b64c277e8f0998105a08c9b91"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bbbb98f03ecd45bd32c4856ed00885ac21237d8"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "201a6ff34a1384b0e195cb3535f366b6cfb544e2f865f0fb68e560ad226cafc0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e13748b2e25a3a517f944c957ae5230997d033e0"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b2d1be375f83b36fe18dc6c2655e43aad2779883ea367dbc7ddf8bc7db382589"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12d3cb7b1cb61283034b0949f16d7a2b0d424f0f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "2da3dfda6c7deb1d711b0aea9dbc8a5bc48142d35f74beef603e4454e7634180"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a2d83ff31572eea6339830d1e2697751e0b8f32"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e3a458746533ffd3548f9cd4f00bfdc9701ccf9017c132ab5cae60afc2c0657a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "219d78608da92f28b92ecf7d9ded6ecadebb27cf"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "835e36ac98cf620efc47b849b199da627b449d156efb7ea9a3ba0dcbf186e112"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8e7266780f7ac605769a298b003a322c1e581d5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "770c09471dda09930568d39297b1e202bf14dcc380d3a42871b08dd697eaf550"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f08590ed54fbdc104cf052240f079bae86b91f7"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "130bbbfbfa8605ec56779eedc47ac2a42363aa8af57ea0bc74adb0526c62eca9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "665cebe60a852efb10a3351e82b925398dfaaac2"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b2374b2bacbcec006445b229a3df98a7834b896db7f0f36ce6e97cadd734b018"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23719f16c95c6a445c45aa4f3eb77ffc5dbb6430"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ab2e6d97941cf3bec866fb8f231dfd0d7a72520158eb77978c2f7ee22d6e71e2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eae9aab3faab2d7cc190ad2483cf2855a8c9ae0c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "470499ebaf7f6caa9ce9b55fa359218a40aed89d793f7d88b3000d60c858bd07"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ef150b288b47e0fbf5ce6b1aabf904663594d5d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1e509ec0e7d034ca4dee5f668456b1774a8cb83cf3098b4f62b2ee4ef1cf03cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "399424e39c44fb20647c1657d4dcd6465ff7bcd6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "df1b5e10c85a711ffe55d48c3774859ff704ff1a11cfdbd8643d8ca1927a248e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "786afdcfe6587ee82f7fc9852f5a6e7517dd6883"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "659b6c9566af8977c3e3a77abb41917aa9c058e63c3b792a33e53e455be9fad2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b27f02cdc9faab5d937f3ae684481065e936f1ac"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "08dc0a44682d5d8f28571e20f48b6b5039b1f5904c905fdf8452653ea76425fe"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15459d9d2bcae923f9aaa74f060b7b2d3cafca71"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "44b604bf15ed3155cb18721557de52d9c83f58408f3a216aa4d3908cf064d1bd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d8c3632f172bca51201986089a0b65abef65427"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "3fa16d4877aee3f41284a414f79a4aecd2b455afb399acfb00193e832447aae7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f060ccf6bd87110d69bc6457188f951e8ff398b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f971f3ec6df93a33089d1793085cbcdbf87e7313d1abef426fe62e4648c9b13d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "eb6467bd97a456b9a529622b8c0320ebcd02080a"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "690ed2369b54b1ea03baf10337cc7e47ea6855a84122caed16e4faf7306abba2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "859cd78ee6743b570eff9d3ad8c3c044fa001713"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "09a338f2da982739a3fbd644188ea997949e5f8c920c8cc37ceb253c54bbd5c1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07627b0f8388970b0bb70a008397f2f52cd3fca1"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ca5af93d1d06c48c1ec96c2de420313214f37738bd2e129d19bcc781368ec3ee"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+0/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
