[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "4dfe688e76a22c8788cbaf218060d92b8d43354e"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "032f11acd005d4b61346417c86b02b3bc2f79716ddb784fd2f499918c649a448"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a7bfa6d8937152799430946ae34cc37d40834c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "464a08a282754662066054bb3fa273b28aebe3bd3ef1e7a102ca94ae33c030b2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c85b7bdaff9ff80a0e9d17f1cea04b403000eec"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "03bce72345bb361c180e54de490637df5a56ac4c04997edd9e269852edbd8577"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "e42dea263fad57d55559d92f7667c5aa0acf4f5b"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9620e19f1aa81fa62eb83ea5e23587b8771ff13200eb621a4acb63667c657bd7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa879ef0b2bf3fe5b5d9c62722511dc4d5ba22a5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b17e416dda4dcb699b97309a4f4fbca3f57670a547ceb33bfac4ba9d6aaf8489"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc643f0163fbb6e15ebef5a91a7bc2f2c7fb523a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "50c25239726dec5be7a2c0a8ce39488f568d66dd65c36f60625301ef554eb7c9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "986a24b456d8b405c7d52d003061fa92c92e53fd"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "110c8306d07516fd9e42ff19256b13a2de8ff857dad74ff49e0aaee94b6ec884"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d14d7f9194c5b8eed121eb03da8ce63b1b6408fe"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "7f9711ba4ff28d3331bbd046c823d751f4eab787ee1b6162cdaa0d9fb06b60ac"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "113c96ce7bf82077aca02de322168ea64c95220c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f795ea06d7fb5dc23a1605b78492780fa898ebe3febbe01a63a85716d1b7d63f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f5ba7957e3e95f1a3fc16e0a49898bb58705ee5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9711a8170665b72550290eb55d85fcc8dc036fcf9611c9a601d1ea1b886731d0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ec1f77e62b3e52f6a675dc79899e6c633edee50"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "0a3f0fb4f7518bb5f362d5ee0282dcd536fa5cd610baf2c836e5424cfae7a19a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fb24da2ecb606d1bd5a486eec6d5de871477b92"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b338651e8a005a893f0dda7488976fbc6c1a7f8dc55b6eb7b456850700012df9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67c0d386c9cd5a4fd4c7bfd57e6982cc2ffbde77"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f52847061cfd2fae5e30206b070a3a4c040c6d6b850d3e2413f9a8bbfd937602"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "535b8e8a2d6a066b592500d972e2aa1662d0d0e8"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4fd06d24b7366a9cd7aa2d6ab80618de85afcec0339949ab45e46a6483dd6bfc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8d461f0813fe0ff4eeec2f609186fdb3e355dce"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "2c4bef48d861b183bb865f064ba89be8b2295864b27840247de42e1ad9b8c6fb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20cebead9a186bb351d4b275385273537cb2d581"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "5150b210aca43644b3c7394789773bfe5f0b2f53d908151d0654d8470482baac"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "2bbf61c2da942f55f585c3323653581f7b0771fd"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1099c6e21069f16fa244697e5c77f0f8d3d7b2b75cafe3a7887b52974918d5dc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8410215e1c94b618824dfe8c831fa5f987a3cde"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "fcaf8f93b1144dc0adb45c5c0a22392d2dd4879ff9eb4eb0fed52f7fc520da0f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v22.1.7+2/SPIRV_LLVM_Backend.v22.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
