[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "cefda002bee32f1a9f221002e003ef5a11c015cd"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c0df69139addf130e43f4fb573593f95a635d357dc8ecb6f00a320076199288b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6097e96296ff460b1c25f1b6b4265a9cda4e7f04"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "257aad9ca662ddf16b82eaa8d5812ff72f3d9a75d917fbb645f19eaf4384432f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0180f4baf527ef898dd17c0c92b27649599e4e50"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "1e64bc9205e8a4cd69849a735ff2a155a086437c857a9bd572bf9d91bfa5ec24"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48f5bd2cf5d1cf91df4ffb298baa11d86f2c6299"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f3af59daa67bc101c5d798aefe88d36f8785e7e1350bc4cdcc2383c826bf3284"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a60318294b5cf193ab0545b23e574d3715b18b2e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "a662f199ecfed754c941240628de4ac8685647f173064ea1694f3b89e1cb9a80"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "f349c92fe4dbd0ccf49be82011ad782dd164cfa4"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "01dfce96d548eeadaac5a906ff89c07440df119510c989f9de0a59d264785666"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee8f30fe23cd74d1f1683df3df10d413eabcee6e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e9b98c7dcf4a26fbebc068c45192b1124b2b901bb38fce6fda56886347f338a9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a37c25b8690c8e07e051161c982edbfb91257f3c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "741da99f39c4c9320cb2d365828e7adc810518007bb0554261fd4fa229c93d7a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc09366f9c0baf0c3f4b1148562c85bd42891f33"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8836c29ddb72f3f077739b44af4c9227d0fd5cb6435bdd41e8a8ac2a836521c1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea6abdf1f7fc4382d6860471f5674acf4ec3466d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "aec1042af0bd1a1216e29601ccd03ead37b578ebb0f198dab41fe085a1a2bc51"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b76e3859a2157485daae93bec7a23dca8ad0780"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "736703d4284752bb9723bc54fafb72ba79300592c58a148fb2635d74ecc28d17"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a03077656b1505a0eadf198a884bfd48d670c131"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "64930f7952526a4d793344799de29eb3a350cec80b1dd8e80626a5ce46bfb860"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04907d6059693ac968c06b64ca46c110106e026b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d795a49e4c43b2cc65971566f74795832e0b168d52c371fe5647fbbb10610b5b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f418d28940dc870cff533bcfc2ccb3ab3cb83ff8"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "50ac462d73ad5cb6004542d5616a318bdfd80ddae81fc5eb25058955680cc91b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80d17da401a53b88894ed38a65ab67baead1d0b3"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "44f0cce3805fac448e7cb9a36315a55e73866bb6055b0194bb0109836e58ca3b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dddcb28fb0b7bd65c99608411801901f27e53aef"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "fcb0b485c42ba7d3525325567ed718f698e2611d1d938aec45ca66b1eba403b8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfa79ca2b002a97b2e0c0c5b54198f36abf2e051"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8ea4e522ff9e4d0cb6f26c58aff37d57924d4f1b4bc2894f1f416e8992bc7523"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b044e85ebebafa172144af49d21e30f098f7e457"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "803b8b00ab0a4580dc0469a850923738e7e95ddbf5c8785c5f8d600942d1eff8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b42236ae90d03fe166b6183c22e0be753665dfaf"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c26d64758de378c2868a1da2f33db4f257c5f30918ac8742cb7914d1e076193e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5cefbfc59fc21186ff52f58c27096617bffa4f0"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6e326d3fcdb443d28aa4e22e5062b93fcd4841db5867dd79a2bef26d19a17857"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbb6c7a92e379bd9f2e4c255f9bfe0d7ed5c5039"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "92fa1247f00dc2e7c204d2a48185a3f65f274e96f17c104e47e43e2019f9f4dc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "759aaf0f8ee31ffbe9f93b64763a89d12b57b506"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e5bd6cf6b44069c14e7cff7ccd1826f034db7d6d40e3c50ee562d6b01272bf8f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f46019e05ab6f7d7543daafe3935f664b6bae78"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "c445b93eeeac144c6c1bfa1d2a73e4226cf7d8ce92ca0d76d1a02743adafd5d4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72d9d2f31a6c74a678d37ea38816958c7eef8aeb"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "0817fbe940c1f45688aef854748683dd82dd7ac02900e70d1b30eb9d056fa6aa"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "9da41f1797db032ba78bfdda7f519178b590be95"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8de29560f848e7948f7bc552ccd4f3e4ba9541d39c8d5cfd2a768522df12f534"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d49d17d741b6c847d2625a7ef7c86c014b9b4e6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9b9c9f107f734af3e04903bbe68804f7a5a7e226854b9f6d66f4d563a07cd19e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ece1d0a58d673fefe9fe5232740bc43b83814c4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "51498d46de5f258678e2aaaa784567b4df1a95fc63589280151f8b5ff4c37378"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b8c264b9996eef54d3179581488d7ecaaeb67f1"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "97bb2a8872d9aa8eead95ed31de4c5a7ce48f162833525efb5fb2d6caa95b209"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f55e54c5fcf66239edc7e3c20a7d788663c4f44"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6b03bfc3948933e9f23ba6d74e3bbeea60a1fa63fa6b742ccc2ceb92aa78bfc5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "8842b0df24b41d907c32a3c3a397b66f51fe2afe"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6d4067bcbd2caa92df866fa826c64ffc1c210b64d31cdc5af2ce85c0365a4d50"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2eb36828132d00f4fc9c5da15630b11482550a0"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "75d1e66b4cc32f7135a80cfc953157097e4e2abb43312e2aa135b50480c07a3d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66c79747550a2c3a9dac507bab095b2435c693dd"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "e14f500f9f01b99711edfcebdb75038150ae895dfbdc516904558dbfb714a57e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+1/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
