[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "589726d658a1b52ddfabbf08c45af8837bdf6daf"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "56f2a36e62932e6e263f849474039ee14ce67f094a41d679eacfd279785fc043"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8b410d4723cd2d799a4b4788b6eb6481c6d4890"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "464d123ff7d82cbaf5ec4b80200eee83414bb84fce7d25247b1ff992dc4e4353"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86d90505cfa573c007a963dc83d38b32d030dc4c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "875da7364692f351790068359f29e3e247bed624a901eb171d82ea998cc56e23"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "037fc93d6fbf4eee02c8b6903810be4b2dfd0086"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "907de7e0a5bdf4cf5b380bad9ff31dff0ab6e15f655a1549e98aecb5c4646cc4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "daafe79e0157cd533cef5a9bdb57ecce64d37e01"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "5abc58abbe254f96dd7fcdd47ef45fbf926ee7ad783bc3cf2ac6912d2a9f323a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54f13f6319cb5d8bf2073ca73984823a71240404"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "794bce1f4ff6a5fffd3a528d5f592f109cc074a8581dfc8c50a3d62acd2ba52c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f571f3aad8f92be99f957d77625b7f59895cb7f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b1ff3e0948de5b50a37e665e3b01da27f26ce375c0f1dfc2b25841994f0add9d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55567f21f5a822d5202c5a0f27dc1908b09cc861"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8e27e4ff467edce7e9be1896ece4f7f59bd68bcedf8f94e125fd6dbbc2ec4bb7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d32cab2602424d27d47a0d5b241e81a99efded60"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "0d54fc65e5f7434e88079b09bd3c69d90bdd240ac0fab2e6315854f5589b4e54"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e022ac6138ab9508cf6c7b48f705a7d8fdd701a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "2f05e74d2a251a2c2fd1fc1277ebd58a203939f16eb33220865893b710551422"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c924314360e25413b1ed2fcc3e10f8db602a2a0"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b5ddfd8b24b37b64566aacd043403a61d1c584be5ca22e686ce35bd979526b75"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40a7d7091ca8b967a00a46e1a1b3e86c2fe2ec07"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "7fd1030cc984ac8a477ffa5b561bc63835b202f0b975b690c2ef5c210ad600c7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "277d377d2cef2d3144748b137bc05e84e26c63db"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "694ba5f74ba4d0fbbb885876c524cdf3bac0df3d9d11c2c315a69d6b8216d6e1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "81f13bc28ba73692a2f5c44d3e63d96612b2fc50"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "bcf4c1dc7ff60fa14980a5da2f6008afe452293b51f5e91b4c5db4342f37fd74"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cf6761a14a26012e3d6c21aa614e74c48f5a2ba"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "41aee7a8d44278cf8306eca01243d8f8d14bb0d39626d65520200c6685584129"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdf41e11ab00c369e4cdeb112a0f48b55f115502"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "cba61f5269b161690984e833e67c6688a62704b0b666b8e6d3451448a6f3f934"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "bb1ca1955a0e286ed66d7b1d4d7cbc3ee2ad4d0f"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "edb12b146287295d912fee6edc8371b2728e81544e80950a28b706e5adbc497c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d4ae16639f08ae9f20f9bcfa195fb68cb6d9c6"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d9051169ec7b0ed94e10f44d433205fbe909b8b43304f098178e87201e08c18b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v23.1.1+3/SPIRV_LLVM_Backend.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
