[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "da121247af677d108164adaade44b42b69dbfe9f"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "72953ee6cc51caee9710ccc92e3f3e9bdc4ae2ac28fc2f061f0fdb8d7e3238cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36b1adccaa0290731a7f395ef9d00ae0ee9832dc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "bb833a1c6c3e39b7006d642149dbc85e6059ea652a230d4014399fce84d2d051"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddac138b9fe286f83a1c2b31b96e16d2b1d5321e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "8a3220b2799abc2b08f8cc91f782af927a4b5cdabc440a06b5bf692d2c23100b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0d960d4a536a6a4451d8eecf7986431be5281ff"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "89a083e5fdbfb7b34faebad35bcfbc6b2719598c73477f1f997af6c6ab888f07"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e5bba7345fadd27b4b807814ce0da4ad409d4ba"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f56503f7ee8ec37ca48a6945c8c6bd1c4b4a24aeb9df2821a8e86f5a5adf8e33"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "aarch64"
git-tree-sha1 = "e187f057447376ccb1d949736310a36e723b7191"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4206286d65ea68e0e1f3d325c93a6f592499759af7265f27e78b9a9b4b0eb999"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c5bb7c2d6243c8412864578d43e15809c168d90"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "52a877c5bff03eda3305ca770656b75b0aff94fa69a637c9b293005d5e6ffeeb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78c2048411c5559dca4e7ed5856909f7c58d680d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "6fea4d2d1892ec2d5a61f574af742dcb943b05a0bee0600bc3912b000c6f1ef2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55acfce960c8bfb900f5ff8a49c11817bebcb724"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "82144613c28f2eafd396813116ef64625d7e979ee90ef1e4b3d8c11f92eccf29"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4fcadb7b2130724687330d97aca1eae67792aa3"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "901221bae6d326a664eb3d992e3b2fe354772e50ac4cad1231b037413d603828"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68565e969190e4a1faf3183a71b65960d502f806"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f1614f0aab84da7317f5595d70c7945fe37dc8fbb7f7631a031976c1017a90d1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed1b259957cf64211edf26143094429795360922"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "920f73bc17c547550423621ec90b7d2e6c68a19c40566fd719c1f216d23e7d3b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdc2a1aa77a7cebf0bf73e975760b94bac2fe6f7"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "4877b1ee4eaf07d124c7184d284fd9862f3161499bfc7760466e90d7d698aa77"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "301a140ae87b6e4f5beab766f6172f4a99994f6b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "89a9006a1cbbac788841816c21a15f77a6b134892e2a0b7203a88ecc3c1610c8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb455106a947c2d88c6724256565d2c4151a480f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d297a6ae537a5a895e31b0628a0e58b1929cdab06f7a284d023d249253f9643b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa2955005c0402bf0c616db351af3900ef535d5b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b76c8b72b21bf10f5fa5f98644f1ceb030858d55a9efeb8fb2cb040a3820ee68"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc3661ed8ae7036e7f5635c0d021ae5c1425b2f9"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "02840763ccd15ba11df696689eeb449e2e79cb7816c0ec7bc25cd7ed506444c1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "686d8d0fde909e2be675385a5eb701285a180e47"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "5e894024c19203f1fdc0b1915905d0123f70f0d05dbda5837cd122fa75eecbae"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e63e6fbcb470ce2de6d982149b34a634bb4d9a3"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "ab90b9d7f51b4c9b12d8a1b29f369467bbd0ad2e439392478382474d362d3aa9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdb5e0a7c6a521b3eb0c41783c56073ea770647e"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "9e9a9ce5cd07276c6551dc2b7043fd26b18c5fa25f6e8675caa588dca4fb12fc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0675183123780334718038f61f5d8d64db89755f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "73b13a107cd4ed51343594c1d912341184afe35bf745416f0401b82c4c06036b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bab502d17d030b8bf781274eec39c258bf5336b5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "dbaa17b19643f3f0b06d2ae776d88b1ae7f60dd5a8c00e518b8123a6c5cc45bd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c11ba58a9037cb380101e8788168c391f0d20c47"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "b115af6a4d4824a962377836418095ca28a85630cbdad63650708536f28811dc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b6f931d2a9ca6735e6e8126116be50fa5da6aaa"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d1affc2b410574b06d9466679da08f8e379cc9b924318f2323c3d83db36e9876"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "b8c3b1c3546bbaafa1d4b9bc7c39f24a18ab2174"
os = "macos"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "57a29c9af6b75ab410f0010fd6c372561785a07c5ec97e6b0875bb90c0442cd7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "841fc2c244f614d312b4f250c9ecde782cc5a2a1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d0764ba29790b1af02b2f6dfe5f0d5ac6135adfc5e1c38ee175dbb0d03aa8318"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d914a1e01c10ece485a7a03d06f4b2ab43303f0f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "d9ebf02dd18231c1f9dba12c171f94ee3e7b0ec2f76582aed4580d2e980b0770"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1a8baf413586f95b4f518f30d8f68a4efc82448"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "96f2fbd229a0fa0b4b498ccc5314940b692d9dd36c370e6cf4b2053b1b2bbe47"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38cd6eb30134b43a3e98e28cc42952dfa64743f6"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "281e3cfc88d3fc3a81be389d3a12eaa0719045d930101758384dbd696aa48f1f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
git-tree-sha1 = "13e003e4ca8ff92c533728e55355ac29441c5647"
os = "freebsd"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "f43baef38b34b4a0c1c77f3ef98e5dc444652440e9f597410b471d59eb7f0bf4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d13390cc2ccc1e54df1af0c6fdfd9ea85f2d19d3"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "219b1d69152fb107d956e9b8058da17d8462d024c1764019162b24a5811fb3ba"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Backend]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc3d851b0a7752bcb545ade493bc39133abddb95"
os = "windows"

    [[SPIRV_LLVM_Backend.download]]
    sha256 = "67ce032bc61793405d0c2cceb4bbf8cc363021e06df8ba0add7d9d078871584a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Backend_jll.jl/releases/download/SPIRV_LLVM_Backend-v20.1.5+3/SPIRV_LLVM_Backend.v20.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
