# Autogenerated wrapper script for SPIRV_LLVM_Backend_jll for x86_64-w64-mingw32-cxx11
export libspirv

using Zlib_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Backend")
JLLWrappers.@declare_library_product(libspirv, "libspirv.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libspirv,
        "bin\\libspirv.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
