# Autogenerated wrapper script for SPIRV_LLVM_Backend_jll for x86_64-apple-darwin
export libspirv

using Zlib_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Backend")
JLLWrappers.@declare_library_product(libspirv, "@rpath/libspirv.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libspirv,
        "lib/libspirv.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
